WITH RECURSIVE GENERATIONS AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT c.ID, p.GENERATION + 1
    FROM ECOLI_DATA c
    JOIN GENERATIONS p ON c.PARENT_ID = p.ID
)

SELECT ID
FROM GENERATIONS
WHERE GENERATION = 3
ORDER BY 1;