WITH RECURSIVE TMP AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT e.ID, GENERATION + 1
    FROM ECOLI_DATA e
    JOIN TMP t ON e.PARENT_ID = t.ID
)

SELECT ID
FROM TMP 
WHERE GENERATION = 3
ORDER BY 1