-- 코드를 입력하세요
WITH TMP AS(SELECT a.ANIMAL_ID, a.NAME, ABS(TIMESTAMPDIFF(MINUTE, b.DATETIME, a.DATETIME)) AS TIMES
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
ORDER BY TIMES DESC
LIMIT 2)

SELECT ANIMAL_ID, NAME
FROM TMP
