-- 코드를 입력하세요
WITH RESULT AS (
    SELECT CAR_ID, CAR_TYPE, (DAILY_FEE *30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단' ,'SUV')
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (START_DATE < '2022-12-01' AND END_DATE >= '2022-11-1')
    )
)


SELECT a.CAR_ID, a.CAR_TYPE, a.FEE * (100 - REPLACE(DISCOUNT_RATE, '%', '')) /100 AS FEE
FROM RESULT a
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN b ON a.CAR_TYPE = b.CAR_TYPE 
WHERE b.DURATION_TYPE = '30일 이상'
AND FEE >= 500000 AND FEE <= 2000000