WITH TMP AS (
    SELECT CAR_ID, CAR_TYPE,(DAILY_FEE *30) AS DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR a
    WHERE CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND (a.CAR_TYPE = '세단' OR a.CAR_TYPE = 'SUV')
)



SELECT t.CAR_ID, t.CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) /100) AS FEE
FROM TMP t
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON t.CAR_TYPE = d.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상' 
AND DAILY_FEE  >= 500000 AND DAILY_FEE  < 2000000
ORDER BY 3 DESC, 2, 1 DESC