WITH TMP AS (
    SELECT c.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY r ON c.CAR_ID = r.CAR_ID
    WHERE r.START_DATE <= '2022-11-30' AND r.END_DATE >= '2022-11-01'
)

SELECT c.CAR_ID, c.CAR_TYPE, 
ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE /100 ), 0 ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON c.CAR_TYPE = d.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE c.CAR_ID NOT IN (SELECT * FROM TMP)
AND c.CAR_TYPE IN ('세단', 'SUV')
AND ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE /100 ), 0 ) >= 500000
AND ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE /100 ), 0 ) < 2000000
ORDER BY 3 DESC, 2, 1 DESC


