-- 코드를 입력하세요
SELECT 
USER_ID, 
NICKNAME,
CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2	) AS 전체주소,
CONCAT(SUBSTRING(TLNO,1,3), "-", SUBSTRING(TLNO,4,4), "-", SUBSTRING(TLNO,8,4)) AS '전화번호' 
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER b ON a.WRITER_ID = b.USER_ID
GROUP BY USER_ID
HAVING COUNT(*) >=3
ORDER BY USER_ID DESC