WITH TMP AS (
    SELECT *
    FROM ONLINE_SALE s
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID
)



SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(i.USER_ID) AS USERS
FROM USER_INFO i
JOIN TMP s ON i.USER_ID = s.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY 1, 2, 3