WITH RECURSIVE GENERATIONS AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT e.ID, e.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GENERATIONS g ON e.PARENT_ID = g.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GENERATIONS g
LEFT JOIN ECOLI_DATA e ON g.ID = e.PARENT_ID
WHERE e.ID IS NULL
GROUP BY GENERATION
ORDER BY 2