WITH RECURSIVE GENERATIONS AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT c.ID, p.GENERATION + 1
    FROM ECOLI_DATA c
    JOIN GENERATIONS p ON c.PARENT_ID = p.ID
) 

# SELECT * FROM GENERATIONS

SELECT COUNT(*) AS 'COUNT', g.GENERATION
FROM GENERATIONS g
LEFT JOIN ECOLI_DATA e ON g.ID = e.PARENT_ID
WHERE e.PARENT_ID IS NULL
GROUP BY g.GENERATION
ORDER BY 2;