WITH RECURSIVE Generations AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT n.ID, n.PARENT_ID, g.GENERATION +1 AS GENERATION
    FROM ECOLI_DATA n 
    JOIN Generations g ON n.PARENT_ID = g.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM Generations
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;