WITH TMP AS (
    SELECT HISTORY_ID, 
    CASE 
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상' 
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상' 
    ELSE NULL
    END AS DURATION_TYPE,
    (DATEDIFF(END_DATE, START_DATE)+1) * DAILY_FEE AS ORIGINAL_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY r
    JOIN CAR_RENTAL_COMPANY_CAR c ON r.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID,  ROUND( ( 1 - IFNULL( d.DISCOUNT_RATE, 0 ) /100)  * ORIGINAL_FEE, 0) AS FEE
FROM TMP t
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d on t.DURATION_TYPE = d.DURATION_TYPE AND CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC

