
WITH TMP AS (
    SELECT c.CAR_ID, r.HISTORY_ID, c.CAR_TYPE, c.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) AS FEE, 

    CASE 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
    ELSE '90일 이상'
    END AS DURATION_TYPE
    
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY r ON c.CAR_ID = r.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
    )

    
SELECT HISTORY_ID, ROUND(FEE / 100 * (100 - IFNULL(DISCOUNT_RATE, 0)),0) AS FEE
FROM TMP t
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON t.DURATION_TYPE = d.DURATION_TYPE AND d.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
