-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT p ON a.PT_NO = p.PT_NO
JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE a.APNT_CNCL_YN = 'N' AND a.MCDP_CD = 'CS'  AND DATE(a.APNT_YMD) = '2022-4-13'
ORDER BY a.APNT_YMD 