WITH RECURSIVE HOURS AS(
    SElECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM HOURS    
    WHERE HOUR <= 22
)

SELECT h.HOUR, SUM(IF(a.ANIMAL_ID IS NULL, 0, 1)) AS COUNT
FROM ANIMAL_OUTS a
RIGHT JOIN HOURS h ON HOUR(a.DATETIME) = h.HOUR
GROUP BY h.HOUR
ORDER BY 1