WITH RECURSIVE HOURS AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM HOURS
    WHERE HOUR < 23
)


SELECT HOUR, IF(o.ANIMAL_ID IS NULL, 0, COUNT(*)) AS COUNT
FROM HOURS h
LEFT JOIN ANIMAL_OUTS o ON h.HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY 1

# SELECT HOUR(DATETIME), COUNT(*)
# FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# ORDER BY 1
