SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN
(
SELECT b.ITEM_ID AS TMP
FROM ITEM_INFO a
JOIN ITEM_TREE b
ON a.ITEM_ID = b.PARENT_ITEM_ID
WHERE b.PARENT_ITEM_ID IS NOT NULL AND  RARITY = 'RARE')

ORDER BY ITEM_ID DESC
