-- 코드를 입력하세요
WITH TMP AS(
SELECT i.ANIMAL_ID, i.NAME, i.DATETIME
FROM ANIMAL_INS i
JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID 
WHERE i.DATETIME > o.DATETIME
ORDER BY 3
)


SELECT ANIMAL_ID, NAME FROM TMP 
