WITH TMP AS (
    SELECT CAR_ID, START_DATE ,COUNT(*) OVER(PARTITION BY CAR_ID) AS CC
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >='2022-08-01' AND START_DATE < '2022-11-01'
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM TMP
WHERE CC >= 5
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH, CAR_ID DESC