SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
WHERE (
    SELECT COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
    AND a.CAR_ID = b.CAR_ID
) >= 5
AND YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY 1, 2 DESC