WITH TMP AS
(SELECT ID, n.FISH_NAME, LENGTH,
RANK() OVER(PARTITION BY FISH_NAME ORDER BY LENGTH DESC) AS RANKS
FROM FISH_INFO f
JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE

)

SELECT ID, FISH_NAME, LENGTH
FROM TMP 
WHERE RANKS = 1
ORDER BY 1