SELECT 
CASE 
WHEN SUM(IF(s.NAME = 'Python', 1, 0)) > 0 AND SUM(IF(s.CATEGORY = 'Front End', 1, 0)) > 0  THEN 'A'
WHEN SUM(IF(s.NAME = 'C#', 1, 0)) > 0 THEN 'B'
WHEN SUM(IF(s.CATEGORY = 'Front End', 1, 0)) > 0  THEN 'C'
ELSE NULL 
END AS GRADE,
ID, EMAIL
FROM DEVELOPERS d
JOIN SKILLCODES s ON d.SKILL_CODE & s.CODE > 0
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY 1, 2